### ISSUE TITLE
Feature request: Include release date next to version number on change log

### ISSUE THREAD

**Issue by rubin110** [svenackermann/Prime-Player-Google-Play-Music#113]
As a user it would be nice to see when particular releases happened so one doesn't miss anything new. :)

**Comment by svenackermann** [comment]
Actually there is already some functionality to tell you about new features:
If you enabled the "Notify on updates" options (whichs is on by default), on updates the PrimePlayer icon will become orange (and stay orange until you click it or open the options page). Also, when you first open the options page after an update, all new/changed options are marked orange and in the changelog all new releases are marked orange.
So you see, it's hard to miss anything new if you only have that option on.

From this point of view I think adding a date to the changelog is quite useless. You would also have to know when you last updated to know what's new. I think it's easier to just read down the changelog until you find sth. that you already know.
