### ISSUE TITLE
Request: Miniplayer window Always On Top option

### ISSUE THREAD

**Issue by t4exanadu** [svenackermann/Prime-Player-Google-Play-Music#114]
Is it possible to implement an Always On Top option for the miniplayer window so that when the window opens it is always on top of the other windows and remains that way? I am currently using additional software to accomplish this (devilspie in Linux and Dexpot in Windows), but would prefer if it was an extension feature, if possible.

**Comment by svenackermann** [comment]
Please see FAQ, [here](https://github.com/svenackermann/Prime-Player-Google-Play-Music/wiki/Advanced-Miniplayer-features), #51, #67, #71 and #75.
