### ISSUE TITLE
Star Ratings not displaying in miniplayer

### ISSUE THREAD

**Issue by t4exanadu** [svenackermann/Prime-Player-Google-Play-Music#122]
This just started happening in the last few days:
![selection_001](https://cloud.githubusercontent.com/assets/3803896/6884914/5f3c80de-d5d5-11e4-9349-f49237f24609.png)

As you can see, the song is rated in Google Play Music, but un-rated in the miniplayer. Sometimes, I can fix this by skipping to another track and then back again, and the rating in the miniplayer will return. But, this doesn't always work.

**Comment by t4exanadu** [comment]
I wonder if this was a temporary issue with Last.fm or Google Play Music, as I am unable to reproduce this. I'll let you know if it happens again, though.

**Comment by t4exanadu** [comment]
OK, I'm still having some problems with the ratings. The miniplayer is still reporting the incorrect number of stars. I have my ratings linked with Last.fm. I tried re-authenticating with Last.fm., just in case, but that didn't seem to fix the problem:
![selection_001](https://cloud.githubusercontent.com/assets/3803896/6889101/c1aca0f0-d65c-11e4-8aba-db76ad22df3b.png)

**Comment by svenackermann** [comment]
I could also repro this, will look into it.

**Comment by svenackermann** [comment]
Many thanks for the report. This should work again with v2.28.1.
