### ISSUE TITLE
Graphical artifacts in album listings?

### ISSUE THREAD

**Issue by t4exanadu** [svenackermann/Prime-Player-Google-Play-Music#123]
I just noticed these orange dots and what looks like some kind of graphical artifact yesterday: 
![selection_001](https://cloud.githubusercontent.com/assets/3803896/6969538/6cfa3c3c-d93d-11e4-8f70-abcadb9785c2.png)

Are they bugs or some kind of feature I don't know about? I noticed the extension hasn't been updated in the last few days, but Chrome Beta for Linux has seen several updates, so perhaps that has introduced these.

I'm having trouble re-producing them, too. It only seems to affect some listings  and only when I go to "All my songs" for some artists in the Google Play Music tab. 

Today, the circles turned to white crosses:
![selection_002](https://cloud.githubusercontent.com/assets/3803896/6969668/599cac00-d93e-11e4-90a9-af308483179f.png)

Any ideas? I haven't tried disabling the extension to see if the circles go away. mainly because I'm too busy listening to music to try it. However, I posted on the Google Play Music product forum about this, and no one else is able to reproduce these (and none of them use Prime Player). So, it seems very likely that it is the extension.

**Comment by t4exanadu** [comment]
One last thing: I wouldn't be surprised if this is a Linux-specific issue. Chrome is notorious for not always working well with the UI rendering system in Linux (there's a huge rendering bug that's been unfixed in Chrome for Linux for a year now that causes "tearing").

**Comment by svenackermann** [comment]
Hi, I cannot imagine how Prime Player could do sth. like that. The images you see aren't even part of Prime Player, maybe they're coming from some other extension.
Please try to disable Prime Player (you need to restart Chrome & reload Google Music afterwards to remove all artifacts) and see if this fixes it. However, I cannot reproduce it and thus I cannot fix it.
If you feel that this is a Chrome related issue, you can post it [here](https://code.google.com/p/chromium/issues/list). If you think it might be a bug on the Google Music site, you can post feedback to Google (last entry in menu when you click on the settings icon on the page top right).

**Comment by t4exanadu** [comment]
Yes, I'm still seeing it with Prime Play disabled, clearly it's not that. I did post something on the Google product forums, and it was suggested that it was your extension (because it's the only Google Music related extension I use, and no one else could reproduce it). Anyway, thanks. It's harmless, so I probably won't bother reporting it as a Chrome issue.
