### ISSUE TITLE
Allow other apps to determine music playing state

### ISSUE THREAD

**Issue by irontoby** [svenackermann/Prime-Player-Google-Play-Music#125]
Hello, I would love to be able to disable my screen saver while listening to Google Play Music, and am curious whether you've considered this feature or have any ideas on how it could be implemented in a platform-agnostic way. Obviously you don't want the headache of trying to disable screensavers on every platform (I'm on Ubuntu 14.04 fwiw) but if there were a way for outside programs to query, "is the user currently listening to music?" or even more generally, what is the current state of Google Play Music? ("stopped" / "playing" / "paused" etc.)

It looks like the best way to do this may be using [external messaging](https://developer.chrome.com/extensions/messaging#external) where your extension would register a message listener, and I'd have to write another extension which then sent a query to Prime Player asking for the current status (it would be great if your extension could just send a general event that anyone could listen to, so I didn't have to poll every so often, but it looks like passing messages requires the sender to specify the recipient).

So when Prime Player received a message like "getMusicStatus", it could return its response, then I'd use Native Messaging to send a command to my screensaver to disable or enable.

Anyway just wanted to see if you'd be open to adding something like this, I could probably even work on adding it myself if you wouldn't be opposed. Thanks!

**Comment by svenackermann** [comment]
Hi,
of course it would be no problem to add sth. like a public API to Prime Player using external messaging. It should also be easy to avoid the polling problem using a [long-lived connection](https://developer.chrome.com/extensions/runtime#event-onConnectExternal) where Prime Player calls [Port.postMessage](https://developer.chrome.com/extensions/runtime#type-Port) for each status change.

The bigger problem would be your part, because you would have to write a [native extension](https://developer.chrome.com/extensions/nativeMessaging) for each platform. I'm not sure if it's worth that much work just to disable the screensaver. It might be easier to [ask the Chrome developers](https://code.google.com/p/chromium/issues/list) to provide an API for that (of course that would take some time).

If you really want to do that, it would be a good start to document the desired communication protocol/messages format between your extension and Prime Player. You can use the Wiki for that.

**Comment by irontoby** [comment]
Ah okay, the long-lived connection idea sounds like a better one. Honestly I wasn't thinking so much of an extension specifically for controlling the screensaver, but more along the lines of an "if this then that" for Chrome. I'd have to think about it a bit more to decide if something along those lines is possible, but if so then I could just let the user fill out whatever action/script they want to take in response to an event.

Thanks for the feedback, if I decide to proceed then I'll indeed write up a proposed format in the wiki.

**Comment by svenackermann** [comment]
Hi, I now implemented an option to keep the screen and system awake using the [chrome.power API](https://developer.chrome.com/extensions/power), see #187. If that is enough, you can close this issue if you like.

**Comment by irontoby** [comment]
Well I'm unable to change any of the dropdown options on the "Look & Feel" tab with the new material design screen; when I click them the current selection just highlights but it doesn't show any new options to choose from.

However I was able to enable this by exporting json settings and changing `keepAwakeLevel` to `display`. When I did this, the feature seems to work great! Screen stays unlocked while music is playing, but if I pause the music then the screen will correctly lock after my OS timeout. I'll close this ticket then since the original purpose has been met.

Is the options UI bug a known issue? I didn't see anything specific to that in #130. I can open a new issue if you'd like; I just tried it on 2 different computers (my main Ubuntu desktop and a Windows laptop) and get the same behavior.

**Comment by svenackermann** [comment]
That's strange. It has nothing to do with #130, this is more related to #178.
Normally when you click a dropdown you should get a popup with selectable values. This uses a polymer element you can try out [here](https://elements.polymer-project.org/elements/paper-dropdown-menu?view=demo:demo/index.html&active=paper-dropdown-menu).

I cannot reproduce this, so I'm afraid I can't do anything against this. This has also not been reported before.
You might check the log in the developer tools. You can open developer tools if you right-click an element in the options popup (not the header!) and select "inspect element" (Ctrl+Shift+I won't work, this just opens the developer tools for Chrome's container for the options page).

**Comment by irontoby** [comment]
Thanks, I've created #189 to document what I found.
