### ISSUE TITLE
Pause music on locked doesn't work under Linux/xscreensaver

### ISSUE THREAD

**Issue by rubin110** [svenackermann/Prime-Player-Google-Play-Music#126]
Pause music on locked doesn't work under Linux/KDE/xscreensaver. If you'd like more info I'm happy to provide it. Thanks.

**Comment by svenackermann** [comment]
This is a bug in Chrome. I'm sorry, but I cannot do anything against this. Please see the [Chrome issue](https://code.google.com/p/chromium/issues/detail?id=476103), you can star/comment it to get their attention to it.

**Comment by rubin110** [comment]
Oh neat, thanks!
