### ISSUE TITLE
[feature request] Miniplayer always on top

### ISSUE THREAD

**Issue by ndsmyter** [svenackermann/Prime-Player-Google-Play-Music#128]
Add the option so the miniplayer always stays on top of other screens (or at least the browser screen).

That way I can have the miniplayer open somewhere in a corner on my screen. I can then always see what music is playing, without having to do anything with my mouse or keyboard.

**Comment by svenackermann** [comment]
Not possible. There are several other issues, just search for "always on top". There is also some explanation in the wiki.
