### ISSUE TITLE
How do I disable Toasts notifications??

### ISSUE THREAD

**Issue by revernus** [svenackermann/Prime-Player-Google-Play-Music#129]
Whenever a new song starts, a notification appears no matter what configurations I use! I already enabled "Do not show toast if Google Music tab has focus", but notifications insist to appear. How do I disable them??? They are so annoying.

**Comment by revernus** [comment]
Well, I had to disable the extension entirely. Please provide some working way to disable notifications completly.

**Comment by svenackermann** [comment]
There is an option simply called "enable toast notifications" right at the beginning of the toast options area that you can uncheck.

**Comment by revernus** [comment]
I'm afraid there isn't such option: http://i.imgur.com/Sm0l08N.png

I'm using the last verion 3.0

**Comment by svenackermann** [comment]
Dammit. There's a bug why this is not visible. I will provide a fix soon. Thank you so much for reporting this. I wonder why it hasn't been reported earlier.

**Comment by revernus** [comment]
Thank you for your attention!
