### ISSUE TITLE
Google Play Music released its big material redesign, parts of the extension are now broken

### ISSUE THREAD

**Issue by WillPresley** [svenackermann/Prime-Player-Google-Play-Music#130]
Let me know if you need full details, from a quick glance:
* Track Title not being read
* Rating not being read
* Playback controls not working

I'm sure you'll see the update and are probably already thinking about the updates, just wanted to get an official Issue in so there's something to close!

Love the extension, it's perfect! Thanks.

**Comment by t4exanadu** [comment]
I just switched Linux distros today and was worried Prime Player somehow wasn't compatible with it (probably impossible anyway). Then I noticed the Material Design UI on Play Music and it suddenly made sense (I like the re-design, but I was never a fan of the orange header and now it seems more prominent).

I also wanted to add that the miniplayer no longer pops up automatically when Play Music opens (as per the setting I enabled). I can confirm all of the other things WillPresley listed too.

**Comment by ErikOsterud** [comment]
I've also noticed that it is no longer scrobbling to last.fm (after disabling, re-enabling and logging out and in to last.fm in Prime Player) the extension states that it was scrobbled but it actually isn't.  It also displays a "track not found" error when viewing the "Love" button.

**Comment by Gnarfoz** [comment]
I can confirm all of these (if that helps any).

The redesign is so horrible. Particularly the floating "current playlist". :-1: 
Hope restoring previous functionality is even possible.

**Comment by svenackermann** [comment]
Currently on vacation. Of course this happens now. I will see what I can fix when I'm back. Thanks for all the reports, that'll help.

**Comment by t4exanadu** [comment]
Yes, the resdesign is not good. I am very saddened by the fact that the 5-star ratings lab is gone. I can't tell you how much time I put into rating all of my music, only to have that work be reduced to a simple thumb up/down. I'm probably just going to suck it up and install my own subsonic server at this point, which is a shame, because I really liked using Prime Player, but this is quite upsetting. :-1: :-(

Thanks Sven, whenever you get around to fixing it would be great. I've been using my phone to play music now, because the Web UI looks almost identical to the Android UI now (so it hardly matters which I use now).

**Comment by jdduke** [comment]
FWIW, "Google Play Last.fm scrobbler" (https://github.com/newgiin/cloudplayer-scrobbler) has basic global keyboard shortcut support that works with the latest update. Might help tide folks over until this (most excellent) extension is updated.

**Comment by Gnarfoz** [comment]
Google's official extension also offers keyboard shortcuts. However, both are missing shortcuts for volume control, which Prime Player has (but currently don't work).
And of course Google's own doesn't scrobble, so for the moment I'm using three extensions for all of this. :laughing:

**Comment by vitriolvm** [comment]
Hi, thanks for your simply great extension and for providing a quick fix after the huge Google Music website update.
Right now the toaster correctly displays the song title and is able to perform pause/resume, while thumb up/down from the toaster is not working at the moment. The thumb up/down is also non-visible neither from the extension icon and the toaster, while the last.fm heart is correctly shown.
Regarding the integration with last.fm the scrobbling now works, what doesn't is the rating syncronization between Google Music thumb up and last.fm love: thumbing up a song does make the song "loved" on last.fm and vice-versa.

Thanks again for such a great work with this extension and sorry for my crappy English :laughing:

**Comment by svenackermann** [comment]
@vitriolvm Thanks for your comment, but as you can see from the changelog not everything is fixed yet. Especially the rating is not easy to repair. Hopefully I will get the rest fixed soon, but I really don't have much time at the moment and I do this in my free time.

**Comment by vitriolvm** [comment]
@svenackermann no, thank **you** for putting efforts on this, for free, in your free time. Didn't mean to push, just trying to provide some feedback, hopefully useful. Thanks again!

**Comment by svenackermann** [comment]
now hopefully everything is fixed

**Comment by vitriolvm** [comment]
Everything is now working flawlessly. Thanks Sven. And once again, excellent work!

**Comment by liubko** [comment]
Thanks @svenackermann !  :+1:

**Comment by Gnarfoz** [comment]
Working great so far, thank you so much @svenackermann!
However, I could only test using developer mode and downloading the .zip from Github.

Version 3.1.2 has so far not appeared in the Chrome Web Store - does Google typically take this long to approve new versions?

**Comment by vitriolvm** [comment]
@Gnarfoz, try chrome://extensions then check "Developer mode" and click "Update extensions now".

Hope this works.

**Comment by Gnarfoz** [comment]
@vitriolvm Doesn't help. :( I tried that before already because I have to enable developer mode anyway to be able to load the .zip from Github.

The Web Store website itself still shows 3.1.1 for me:
https://chrome.google.com/webstore/detail/prime-player-for-google-p/npngaakpdgeaajbnidkkginekmnaejbi?utm_source=chrome-app-launcher-info-dialog

Are you using some kind of staged rollout feature, @svenackermann?
(I don't know if the Chrome Web Store even offers such a thing. ^^)

**Comment by vitriolvm** [comment]
Well, 3.1.1 is the release I've installed at the moment. I don't think Sven already release a newer version. 3.1.1 fixes everything to me.

**Comment by Gnarfoz** [comment]
That's... extra weird, then.
https://github.com/svenackermann/Prime-Player-Google-Play-Music/releases has 3.1.2 and with 3.1.1 I can't change volume through Prime Player.
(Using Chrome 44 dev.)

**Comment by vitriolvm** [comment]
I'm sorry, didn't realized there was a even newer version. I don't use the features fixed in this update so for me everything is working fine. Perhaps you just need to wait for the new release to be available in the Chrome Store just like in Android Play Store.

**Comment by svenackermann** [comment]
3.1.2 is currently in Googles review process. This takes about one day.

@Gnarfoz There was no change between 3.1.1 and 3.1.2 about the volume control. There was only some weird issue that the song progress didn't change when the Google Music tab was not visible. Although the volume control and song progress work almost the same way, it worked for the volume control. Could you check if you can change the volume via miniplayer/shortcut when the tab is visible?

**Comment by Gnarfoz** [comment]
I don't think it worked, even with the tab visible. If Chrome hasn't updated/replaced my 3.1.1 by the time I get home tonight, I'll re-check.
It works with 3.1.2 (installed in developer mode) in any case.

**Comment by Gnarfoz** [comment]
The store version updated before I got home, so I can't re-check.
However, as expected, everything works beautifully with 3.1.2.

Thanks again!
