### ISSUE TITLE
Miniplayer Borderless Window Display

### ISSUE THREAD

**Issue by VeXHarbinger** [svenackermann/Prime-Player-Google-Play-Music#132]
First of, great job, excellent work.

I was wondering if it's possible to get the miniplayer to display in Google's new borderless window style.  I assumed it was the panel option, which I did enable, but it still displays in a framed window.

**Comment by svenackermann** [comment]
Sorry, I don't know what you mean.
If you want to use panels, you have to enable a flag in chrome://flags as described in the hint on the miniplayer type option (when you have set it to "panel").

**Comment by Gnarfoz** [comment]
Probably like this: http://stackoverflow.com/a/25545790/687704
The official GPM extension was like that until recently. It now has a regular Windows border for me. Not sure why they changed that.

(You're right about the panels flag, of course.)

**Comment by svenackermann** [comment]
@VeXHarbinger if you did mean what @Gnarfoz mentioned (like the official GPM miniplayer): That is not possible for an extension (like Prime Player), just for apps (like the GPM miniplayer). The difference between Chrome extensions and Chrome apps might not be easy to understand for non-developers, but believe me: Prime Player would not be possible as an app.

**Comment by VeXHarbinger** [comment]
I freely admit I'm not a chrome extension developer but, yes that issue does sound like the one.  All I know is that the other day when your extension was broken due to their latest code release, I had that borderless window.  Then when your ext began working again that bordered window appeared.  I had hoped that the panels were able to produce the borderless window.

I know it's a different animal but, when I've had to do xaml windows in c# they had a display property on the window for bordered & borderless and had hoped the solution would be just as simple in this case.  Owell and thank you all for the prompt replies.

**Comment by VeXHarbinger** [comment]
I'm sorry, upon further retrospect I'm completely incorrect.  Your mini-player does have a borderless window, it's just google play's pop-out window that I'm talking about.  I guess I just assumed that your ext was interacting with their window for some reason and causing the border.  I suppose I just jumped to that conclusion because your fix and their change happen for me at the same time.  I apologize for not doing my due diligence from the start/

**Comment by Gnarfoz** [comment]
Yeah, that's what I meant earlier. The pop-out player changed designs.

From this (no window decorations):
![image](https://cloud.githubusercontent.com/assets/65654/7754623/5bf57726-ffee-11e4-9d11-a4033fe02dce.png)

To this (regular window decorations):
![image](https://cloud.githubusercontent.com/assets/65654/7754628/6682b50a-ffee-11e4-956f-453e15905748.png)

Funnily enough, the page you get when you disable/remove the extension still shows the old design.

But:
It's the same extension as before. Were they cheating somehow?

**Comment by VeXHarbinger** [comment]
I read a reddit article on this topic, I guess part of the cause for the change is now the player can play without the google tab being opened.  not sure how the window decoration affected that aspect of the functionality but, thus far it's the only info I found.  Shame the old style was very elegant.

**Comment by VeXHarbinger** [comment]
The new player looks great!
