### ISSUE TITLE
Minor graphic issue: Prime Player icon is aliased and "not fancy".

### ISSUE THREAD

**Issue by vitriolvm** [svenackermann/Prime-Player-Google-Play-Music#133]
I'm taking advantage of your availability and kindness, I know, but as someone who is working in the software industry I can guess that improving your products is something you care of.

So here we go.

![screenshot 2015-05-21 16 49 38](https://cloud.githubusercontent.com/assets/12512372/7752016/831359ce-ffdd-11e4-9962-aa0d2874b94c.png)

As you can see in the attached image, in the top right corner of the screen the "orange headphones" icon is a bit "aliased" and not well displayed (as if the original image is in a different resolution and then it is resized inside the button). In the bottom-left corner of the image however, you can see the same image, same size, but well displayed. These are the two of them, side by side, on the left is the "smooth one" shown in the examples of the configuration page, on the right the one displayed in the actual Prime Player button.

![icon](https://cloud.githubusercontent.com/assets/12512372/7752024/8d18d868-ffdd-11e4-93ae-de6f76d1e7c9.png)

I know, very few differences but it's contours looks a bit too sharp, maybe it's just me but i wanted to share. This happens since one of the last big updates of the extension (i can't say exactly which one) and applies for each of the "headphones" icons, not only the orange one.

Thanks!

**Comment by panpipe** [comment]
Hi vitriolvm,

I'm not the developer but I helped update the icons as part of the 3.0 update. I can see your problem, the funny thing is, they're actually the same image (correct me if I'm wrong Sven). I guess the difference is that the in-page image treatment is better than chrome's UI. The browser is nicely scaling the image down in the options but then not doing a great job with that button.

I updated the icons for HiDPI displays (retina etc.) and it seems this has negatively impacted normal DPI displays.

I'll leave it to Sven to decide if anything can be done, but I'm willing to help again if I can.

**Comment by svenackermann** [comment]
Hi,
I tried a bit around and decided that I will leave this as is. There's no easy way to fix this. I don't have a hi-res display and cannot even see a real difference without zooming in.

Actually the problem here is not the scaling. The aliased image is the price for the dynamic browser icon. You know that icon can have different overlays for the playing state, rating, progress and so on. Therefor, the original image (that you see on the options page) is painted on a so called canvas and then the overlays are painted above. Unfortunately, this painting operation changes the look of the icon a bit, even if there is no overlay (so only the icon is painted onto the canvas). That's more a Chrome issue than a problem in Prime Player.

Anyway, thanks for the report.

**Comment by vitriolvm** [comment]
Thanks @panpipe and thanks @svenackermann.

Sven, I just want to point out that this weird icon behaviour wasn't present with the earlier version so I'm not sure this has something to do with the dynamic nature of the button, otherwise it would have been present since the beginning. Which wasn't. Since panpipe refers to an update of the icons for HiDPI displays, perhaps this "issue" is related to that (maybe in combination of the dynamism of the button).

I don't know, maybe there's a way to make Chrome choose the proper set of icons related to the current DPI. Either way, thanks!

**Comment by svenackermann** [comment]
Hi again,

actually there is a way to provide different icons for hi- and low-res displays. But to use that, I would have include each icon in hi and low resolution and also do the painting process for both versions. That would make things much more complicated (as they already are), so I decided to provide only the hi-res version and let Chrome scale it down automatically for low-res displays. It's just a matter of benefit vs. cost and the aliasing is not that bad in my opinion.

**Comment by vitriolvm** [comment]
I agree, the "problem" is not a problem. If it's too work it doesn't worth it for the appearance of the button is not bad at all.

Thanks again.
