### ISSUE TITLE
Rating synchronization between Google Music and Last.fm isn't working properly

### ISSUE THREAD

**Issue by vitriolvm** [svenackermann/Prime-Player-Google-Play-Music#134]
Hi again.
I noticed a flaw in the rating synchronization and I took some time to do some testing. These are the results.

The synchronization works when:
- the song is rated through the extension itself (Prime Player toast notification, Prime Player popup, Prime Player miniplayer)
- playing a "thumbed up" song

The synchronization doesn't work when:
- the song is rated from Google Music web page
- the song is rate through Google Music miniplayer

Hope this helps.

Thanks again for your work.

**Comment by vitriolvm** [comment]
Update:

Removing the "thumb up" doesn't remove the "love" of a song, doesn't matter from where you are doing it (either from Prime Player tools or from Google Music itself).

**Comment by svenackermann** [comment]
Hi, thanks for your report.

Auto-love works fine for me when I rate sth. thumbs up on the GM web page (either from the player area at the bottom or from the playlist).
Googles miniplayer is not supported by Prime Player, I have no control over this thing.

Finally, it is desired behavior that removing "thumbs up" does not automatically remove the "loved" status (it is mentioned in the hint for the sync ratings setting on the options page). This is because you would not be able to rate a song independently in last.fm and Google then anymore. But I could provide another option for that.

Please see also #107 where I explained a lot about the ratings synchronisation.

**Comment by vitriolvm** [comment]
Hi.
I looked at #107 and read the info about the "link rating" on the Prime Player option page. Thanks.

Anyway I believe I'm experiencing a weird behaviour of the extension regarding this feature. I tried uninstalling the extension but this didn't helped.

I tested it thoroughly and I found the following.

When a fresh song is rated "thumb up" from the bottom of Google Music tab:
- Prime Player icon shows the "thumb up" (as I choose in the PP preference page)
- The song is not loved on Last.fm

When a fresh song is rated "thumb up" from the queue or from the playlist/album view of Google Music tab or from Prime Player miniplayer/toast:
- Prime Player icon shows the "thumb up" (as I choose in the PP preference page)
- The song is loved on Last.fm

Do you have any clue about this? Thanks!

**Comment by svenackermann** [comment]
Hi again,

this was an issue that I already found and fixed, it will be coming with the next version. Sorry, I forgot about that, this was the reason why I couldn't reproduce the issue with my local development version.

**Comment by vitriolvm** [comment]
Hi again Sven.

The problem with rating synchronization when rating through GPM page seemed solved with the last release, but in fact it is not.

It has worked once, after I received the update: I reloaded GPM page and rated thumb up the playing song, this made the song also loved on Last.fm. I tried "un-thumb up", the "love" disappeared (I checked the option to reset ratings, thank's for that btw!). I then tried with another song but the sync never worked again. I can't figure out why.

Moreover, and maybe there's a connection here, when showing the PP popup from the extension icon I can't see the thumbs for the rating. I can see them if the popup is triggered while a song is already rated, but I can't otherwise as you can see here:

![screenshot 2015-06-19 15 03 24](https://cloud.githubusercontent.com/assets/12512372/8253928/93161820-1694-11e5-909c-df094caeec34.png)
![screenshot 2015-06-19 15 03 33](https://cloud.githubusercontent.com/assets/12512372/8253927/9315bfa6-1694-11e5-879d-921c4ea290ca.png)

Ciao!

**Comment by svenackermann** [comment]
Hi, I think I introduced a bug with 3.2, will fix that on monday. Til then you can turn the new experimental star ratings feature on. Just rate 1 star for thumbs down and 5 stars for thumbs up. This should work.

**Comment by vitriolvm** [comment]
Will try that. Thank you once more

**Comment by vitriolvm** [comment]
Hi again.

With the last release (3.2.1) the problem with the missing "thumbs" for unrated songs in the PP miniplayer is solved. Unfortunately though, the synchronization still don't work when I rate a song from GPM web page but only when done through PP itself (miniplayer or toast notification).

Can I possibly be the only one? Sorry to keep bother!

**Comment by svenackermann** [comment]
Sorry, but I cannot reproduce this with 3.2.1. Synchronisation (thumbs up -> loved) works fine for me, no matter if rate from miniplayer or Google page (player area or playlist), no matter if star ratings enabled/disabled.

**Comment by vitriolvm** [comment]
Yes, I did reloaded the Google Music page but still isn't working.

Here's what I do:
- Start playing an un-rated song
- Rate it through the bottom-panel of Google Music page (or playlist/album view, same behaviour)
- I see the "thumb-up" icon appear in the Prime Player icon
- No synchronization happens
- I skip to another song
- Start playing the previous song (now rated up)
- I see the "thumb-up" icon appear in the Prime Player icon
- After a second I see appear the "heart" icon in the PP icon: synchronization successful
- Instead, rating through PP miniplayer or toast works flawlessly

Since I flagged "reset rating" in the options menu, un-like a song has the same behaviour: doesn't work done through GM web page but it does if un-liked through PP miniplayer or toast notification.

Can I help you with more informations?

**Comment by svenackermann** [comment]
OK, now I could reproduce (and fix) it. But I only had problems with the thumbs buttons at the bottom player area, the thumbs in playlists worked fine for me. Can you verify that you really also have problems with the playlist buttons?

**Comment by vitriolvm** [comment]
I'm sorry, you're right, it works fine from the playlist/album view.

Thanks once again!

**Comment by vitriolvm** [comment]
Sven, just updated. The rating sync works flawlessly. Great work, thanks!
