### ISSUE TITLE
Add option to open the toast when "Pause" Media Key is pressed.

### ISSUE THREAD

**Issue by TheSoftwareDev** [svenackermann/Prime-Player-Google-Play-Music#137]

**Comment by svenackermann** [comment]
Hi, can you provide more details? What should this be good for?

**Comment by TheSoftwareDev** [comment]
In many desktop media players, the toast opens when a song is
paused/resumed via the media keys. From a feature comparison standpoint,
this would be a "nice to have".

This provides a way to quickly identify the song without opening the
mini-player, and also providing a visual cue that the pause media key
worked correctly when pressed.

**Comment by svenackermann** [comment]
OK, I understand. Since this is quite easy to do, I will add an option in 3.3.

**Comment by TheSoftwareDev** [comment]
:+1:

**Comment by TheSoftwareDev** [comment]
Testing in 3.3. Works great, except: If the Toast currently open, and the pause/play media key is pressed, the toast disappears and immediately re-opens instead of just remaining open

**Comment by svenackermann** [comment]
I know about that. The problem is that I don't know if the toast is visible or not. Chrome moves it to the notification area after some time where you cannot see it directly. The only way to be sure that the toast becomes visible again is to close and reopen it.
