### ISSUE TITLE
Audio plays out both from local speakers and Chromecast

### ISSUE THREAD

**Issue by rubin110** [svenackermann/Prime-Player-Google-Play-Music#138]
Prime Player 3.2.1
Chrome Unstable 45.0.2438.3 dev (64-bit)

When streaming to a Chromecast and hitting the next song (be it the first song or when switching to a new song), the music will start playing both out of my local computer speakers and the Chromecast. If I pause the music it'll stop playing through Chromecast, but continue playing locally. Additionally the player's UI will act as if the song is pause and wont stop the local music until I refresh the page.

Disabling Prime Player seems to fix this issue. Using either the stable or beta version of the Google Cast plugin makes no difference.

**Comment by svenackermann** [comment]
Sorry, I do not support Chromecast, I don't have such a thing. I also do not support unstable channels of Chrome.
Note that Prime Player cannot control if/where music is actually playing, it only hits the play/pause button and watches the progress bar.
