### ISSUE TITLE
Add support for shuffling a playlist by album rather than by song

### ISSUE THREAD

**Issue by johnlcox** [svenackermann/Prime-Player-Google-Play-Music#140]
A feature I would love to have with Google Play Music is the ability to select a playlist and have it shuffled by album rather than by song. It would then play a full album in order before randomly selecting a new album. If this is even possible, it might be easiest to do this by simply changing the order of the playlist but keeping individual albums together.

**Comment by svenackermann** [comment]
Hi, sorry but that is indeed not possible. Prime Player is not able to change the order of a playlist,  album, radio station or the queue. It can only start them or shuffle them using Google's shuffling.
