### ISSUE TITLE
Disable the Next/Prev Track buttons when Google Play does

### ISSUE THREAD

**Issue by TheSoftwareDev** [svenackermann/Prime-Player-Google-Play-Music#142]
On the free version of a Google Music Radio station, the Previous Track button is disabled all the time, and the Next Track button is disabled (when a user hits the max number of skips).

![image](https://cloud.githubusercontent.com/assets/360143/8785348/1af9096e-2ef5-11e5-80c6-be93c4bc4cbc.png)

It would be nice if the mini-player and toast notification displayed the same, as an indicator that I cannot skip forward or backward.

**Comment by svenackermann** [comment]
Hi, sorry but I don't even know how to get there. With a free account I do not have sth. like radio stations. All I have is "Listen now" and "My library". Can you give me a hint/URL or sth.?

**Comment by TheSoftwareDev** [comment]
Sure. Here's an example URL

https://play.google.com/music/listen?u=0#/wst/situations/Lyd5slepfnrcbmhvctrh3yhk4va

**Comment by svenackermann** [comment]
Strange, I do not have these options in the free version. They only exist in the unlimited version, but there's no "Shop" link and of course stations aren't limited.
However, I can watch the state of the back and ff buttons in Google Music and update them in the miniplayer accordingly.

**Comment by TheSoftwareDev** [comment]
It looks like how the next/prev button state is being watched is working inconsistently.

This is the state of the next button when I've reached the end of a playlist of music I own:
![image](https://cloud.githubusercontent.com/assets/360143/8853325/250712e0-3128-11e5-8fb4-e4ad6b5fddd6.png)


This is the state of the next button when I can no longer skip forward on a free radio station:
![image](https://cloud.githubusercontent.com/assets/360143/8853397/6e2df1be-3128-11e5-92b4-da6e187713c9.png)

It looks like the GMusic page is alternating between `style="pointer-events: none"` (the button can't be clicked) vs `class="disabled"` (the button can be clicked but does not skip to the next track).

**Comment by svenackermann** [comment]
Argh. Actually I'm looking for the 'disabled' attribute. But it seems that is not present in your 2nd version. I will fix this, but I'm on vacation for  the next 4 weeks.

**Comment by TheSoftwareDev** [comment]
Enjoy the vacation!

If I can find some time this week, maybe you'll have a pull request waiting for you when you get back. :smile:
