### ISSUE TITLE
Keyboard shortcuts to add current song to playlist

### ISSUE THREAD

**Issue by andrey-shikhov** [svenackermann/Prime-Player-Google-Play-Music#145]
It will be great if there was a possibility to assign key shortcut to add current song to playlist.
I see 2 ways - 
1) hard bind to selected playlist by shortcut, for example ctrl+shift+1 - first playlist, ctrl+shift+2 - second, etc
2) if possible - popup with list of playlists and after click on playlist addition is performed, sort alphabetically excluding other people playlists and first in list playlist where previous song was added - useful when you are listening to the radio station of one genre and saving tracks you like into playlist for more refined list to listen to on repeat)

**Comment by svenackermann** [comment]
It's not possible at all for prime player to add the current song to a playlist or to edit / delete playlists.
