### ISSUE TITLE
Songs no longer detected

### ISSUE THREAD

**Issue by DexterHaslem** [svenackermann/Prime-Player-Google-Play-Music#146]
Since a few days ago prime player no longer detects music playing state. I don't have unlimited so I'm unable to check that, but free streaming no longer is working. see http://puu.sh/judXD/269366161a.jpg for example.

**Comment by svenackermann** [comment]
I'm on vacation for 3 more weeks. I will look into it as soon as possible. Sounds like a change in the Google site.

**Comment by DexterHaslem** [comment]
Nevermind, it started working again! Not sure what happened before but nevertheless. Hope you have a good vacation.
