### ISSUE TITLE
Lock Screen with Windows 10

### ISSUE THREAD

**Issue by LandrinLong** [svenackermann/Prime-Player-Google-Play-Music#149]
I have a PC with Windows 10 that the option to pause playback when the computer is locked does not work.  The music will keep playing.

**Comment by svenackermann** [comment]
I cannot do anything against this. This is a bug in Chrome, please report it here: http://code.google.com/p/chromium/issues

You can tell them that `chrome.idle.onStateChanged` seems not to work on Windows 10.

**Comment by LandrinLong** [comment]
Thank you.  I've opened Issue 524663
<https://code.google.com/p/chromium/issues/detail?id=524663> with Google.
