### ISSUE TITLE
When the Google Msuic for Chrome Extension is installed, media keys are duplicated

### ISSUE THREAD

**Issue by TheSoftwareDev** [svenackermann/Prime-Player-Google-Play-Music#152]
Issue: When the [Google-official Play Music Extension](https://chrome.google.com/webstore/detail/google-play-music/icppfcnhkcmnfdhfhphakoifcfokfdhg?hl=en) is installed alongside Prime Player, media keys are captured by both extensions, duplicating the action 

e.g. 

1. While playing, press `Play/Pause` key, and the music pauses and then immediately resumes.
1. While playing, press `NextTrack` key, and the music skips two tracks.

I don't know if this is possible to detect / fix, but I figure I'd log it just in case, as the official chrome extension is now the way Google is advertising uploading music from your computer to your Google Play account (in lieu of the Google Music Manager application).

Workaround: disable/uninstall the official Google Play Music Chrome Extension.

**Comment by svenackermann** [comment]
Better workaround: assign the keyboard shortcuts for both extensions like you need them: chrome://extensions/configureCommands

This is nothing I can fix. You could call that a bug in Chrome, it shouldn't let you assign a key twice (even not the default keys of the extensions). You can report/look for a bug in Chrome here: https://code.google.com/p/chromium/issues/list.
