### ISSUE TITLE
Feature Request: Do something when the end of a playlist is reached

### ISSUE THREAD

**Issue by rubin110** [svenackermann/Prime-Player-Google-Play-Music#153]
Use case: I'd like it for when the player hits the end of a playlist (when repeat isn't enabled) to continue on playing music, either from a specific playlist, or a radio station, or from the I'm Feeling Lucky playlist generator.

Thanks!

**Comment by svenackermann** [comment]
I really don't have much time at the moment, but I'll consider this.

**Comment by svenackermann** [comment]
The only actions that make sense for me are "feeling lucky", "close miniplayer" and "close Google Music". Starting a specific playlist or radio station would require some extra UI to select the playlist/station which is too much overhead. Also, I don't think that one would like to always have the same playlist being started.

**Comment by rubin110** [comment]
I could see myself wanting a completed playlist switch over to the "Thumbs up" auto playlist on shuffle.

**Comment by rubin110** [comment]
Working great! Thanks! The only tweak I would do is add in an option to force random on the whole playlist when it hits this mode.
