### ISSUE TITLE
Star ratings are gone from miniplayer

### ISSUE THREAD

**Issue by andyforceno** [svenackermann/Prime-Player-Google-Play-Music#154]
I noticed today that the star ratings have disappeared from the miniplayer (I still have the experimental star ratings option checked). I hope this doesn't mean Google has done away with access to our star ratings :-(

**Comment by svenackermann** [comment]
There was a change on the Google site. It seems like it's only a smal change but with big impact to Prime Player.
Besides the star ratings the following things should also not work anymore:
* start/resume/rate a song from a playlist (not the current song)
* parts of rating synchronisation with last.fm
* loading/display of queue in miniplayer
