### ISSUE TITLE
Change Miniplayer Title to Current Song

### ISSUE THREAD

**Issue by mcgrathg** [svenackermann/Prime-Player-Google-Play-Music#159]
Is it possible to change the miniplayer's title from "Prime Player" to the current song info?  This would allow me to easily see what song is playing when the player is minimized.  

Thanks for all of the hard work! I use this extension every day. This is one of the few Chrome extensions I've donated to.

**Comment by svenackermann** [comment]
I do not have much time at the moment, but I'll consider implementing this.
