### ISSUE TITLE
Getting (presumably) false positives from AdwCleaner

### ISSUE THREAD

**Issue by WildGenius** [svenackermann/Prime-Player-Google-Play-Music#161]
Just wondering, why is Prime Player picked up as malware by AdwCleaner? Is it the lyric fetching?

**Comment by svenackermann** [comment]
Reported in user forum: https://toolslib.net/forum/viewthread/1387-false-positive-prime-player/

**Comment by svenackermann** [comment]
From user forum:
> Hello,
> FP have been fixed. Sorry for the inconvenience.
