### ISSUE TITLE
Album art not displaying in miniplayer

### ISSUE THREAD

**Issue by andyforceno** [svenackermann/Prime-Player-Google-Play-Music#163]
In the last day or so album art stopped being displayed in the miniplayer. All I see is the grayscale placeholder image with the Prime Player "P" logo instead. It looks some other things are missing from the miniplayer too, as there is a lot of blank space. I guess the thumbs up and down icons.

**Comment by svenackermann** [comment]
duplicates #162
Can you confirm this is fixed with 3.7.1?

**Comment by andyforceno** [comment]
Yes, the album art and song title are shown again.
