### ISSUE TITLE
No lyrics when switching to "Album art" or "Particles" views

### ISSUE THREAD

**Issue by orlandoryo** [svenackermann/Prime-Player-Google-Play-Music#164]
It works great on the default view (list of songs) but not on "Album art" or "Particles" views.

Amazing work nonetheless!

**Comment by svenackermann** [comment]
Please switch to the default view or view the lyrics in the miniplayer in this cases. I cannot support everything.

**Comment by orlandoryo** [comment]
I understand, but you might be able to pull it off at some point. Anything is possible, no need to be rude about it.

**Comment by svenackermann** [comment]
Sorry, shouldn't sound rude. I just don't have much time for this extension anymore and this quite a special requirement, so I decided to reject it.
If someone decides to help me and maybe creates a pull request, I'm willing to include a fix.

**Comment by orlandoryo** [comment]
Thanks a lot for the fix, man! Already using it! :+1:
