### ISSUE TITLE
Miniplayer Settings - 'My Playlists' link not working.

### ISSUE THREAD

**Issue by skyadd** [svenackermann/Prime-Player-Google-Play-Music#167]
The 'Listen Now' page opens instead of the 'My Playlists' page when clicking on either the mini player's album cover or song title link, despite being set under the "Miniplayer Settings" options ("Open on click on album cover" and "Open on click on song title").

--------
**Side Issue:**
When mini player is set to "Open links in the miniplayer", the "My Playlists" window would appear properly after clicking on the album cover or song title if set to do so.

However, the mini player does not allow the user to play songs.  Selecting on a song would redirect the miniplayer to the lyrics page.  Not sure if this is the intended functionality.

Running: Version 49.0.2623.23 dev (64-bit) (Mac OSX El Capitan)

**Comment by svenackermann** [comment]
Hi,
thanks for your report.

The page where you see your playlists (https://play.google.com/music/listen#/wmp) did not exist when I included that feature. So, it was never planned that you can open your playlists in Google Music. This is handled differently than other lists that can be loaded in Google Music, it was only meant to be opened in the miniplayer (the lists are read from the side menu on the left).
Now I will change the behavior, such that the page mentioned above will be opened when you want the playlists to be opened in Google Music. This should fix your issue. It will come with next version.

For your 2nd issue: Clicking the title in playlists always opens the lyrics, that is correct (see [here](https://github.com/svenackermann/Prime-Player-Google-Play-Music/wiki/Advanced-Miniplayer-features#open-lyrics-from-anywhere)). If you want to start the song, you have to click the album icon at the left side of the song.
