### ISSUE TITLE
(Feature Request)

### ISSUE THREAD

**Issue by vaderj** [svenackermann/Prime-Player-Google-Play-Music#169]
Within the Desktop Notification popup, would it be possible to make the Song Title, Album, and Band name a hyperlink, so it has similar behavior as the Mini-Player ?

**Comment by svenackermann** [comment]
Hi there,
unfortunately that is technically not possible. The notifications are provided by Chrome, I can only fill them with some data to be displayed and assign up to 3 custom actions to it (2 buttons, 1 click for on notification itself).
