### ISSUE TITLE
Regression: ctrl click is not opening last.fm page anymore in miniplayer

### ISSUE THREAD

**Issue by andrey-shikhov** [svenackermann/Prime-Player-Google-Play-Music#170]
In miniplayer options there is no settings for ctrl click and ctrl click now focuses google play playlist instead of opening last.fm page :(

**Comment by svenackermann** [comment]
Hi, I can't reproduce this. Are you sure that your keyboard (ctrl key) works correctly? There is no option for the ctrl-click, it never existed.

**Comment by andrey-shikhov** [comment]
I tried again and it started working. I will try to reproduce, but I think this issue can be closed for now
