### ISSUE TITLE
Auto add thumbs up to library

### ISSUE THREAD

**Issue by lucfig** [svenackermann/Prime-Player-Google-Play-Music#171]
Hi,

First of all thanks for the great extension!
I would like to know if is possible to auto add musics to the library when it is marked with thumbs up.
Regards,

**Comment by svenackermann** [comment]
Hi,

thanks for your report.
I guess that would be technically possible. Unfortunately, this is quite complicated and a solution would be really error-prone. In general, manipulating your library is sth. that Prime Player was never meant for.
Sorry, I won't add such feature.

**Comment by lucfig** [comment]
OK. Thanks for the response.
Em 7 de mar de 2016 3:48 AM, "Sven Ackermann" <notifications@github.com>
escreveu:
