### ISSUE TITLE
[Feature] Star rating future-proof idea

### ISSUE THREAD

**Issue by ignat980** [svenackermann/Prime-Player-Google-Play-Music#174]
#### General information
- Chrome version: Version 49.0.2623.87 m (64-bit)
- Prime Player version: 3.10
- operating system: Windows 7 64 bit and Mac OSX 10.10.5
- country where you are using Prime Player: USA
- labs enabled in Google Music (if any): None

#### Description
Use playlists for star ratings, then render the stars in the UI.
So instead of messing around with a possibly soon to be broken API, you could just make 5 playlists (1 star, 2 stars, 3 stars, 4 stars, 5 stars) and have 5 stars (buttons) next to the thumbs. Then, when you click on a star icon, it adds the current song to the specific star playlist. When a song is played you can query for how many stars it has, or even locally cache that data. The stars then show up next to each music item in any playlist. I'm not sure how you would sort by stars in a playlist, could be a future feature.
Seeing all 5 or 4 star rated songs is already solved! Just click the relevant playlist! They do have a "Thumbed up" playlist, right?

It is unlikely for them to deprecate playlists ;)

Please include affected components (e.g. miniplayer, popup, options page, toast, keyboard shortcuts, Google Music site).
Probably everything would be affected by this change.
The big thing is figuring migration from the old api to this new playlists idea.

**Comment by svenackermann** [comment]
Someone else already had the same idea, see #136. This is just too complicated and error-prone.
