### ISSUE TITLE
Add To / Remove From Playlist Button / Keyboard Shortcut

### ISSUE THREAD

**Issue by karanbir88** [svenackermann/Prime-Player-Google-Play-Music#196]
It would be great if I could hit a mini-player button or keyboard shortcut to automatically add a song to / remove a song from a playlist. The Add-To playlist can be configured to work with a pre-defined playlist, and if complicated, can be built in later, but the Remove-From playlist option would be awesome. I would definitely be happy to pay a bit for this feature.

**Comment by svenackermann** [comment]
see #145
