### ISSUE TITLE
Extension is no longer available

### ISSUE THREAD

**Issue by zainbhaila** [svenackermann/Prime-Player-Google-Play-Music#218]
#### General information
- Chrome version: 75.0.3770.100
- Prime Player version: latest
- operating system: windows
- country where you are using Prime Player: united states
- labs enabled in Google Music (if any): 

#### Description
The extension is no longer in the chrome store. It can't be installed anywhere. Is this project dead? If so, can I publish a copy of it to the chrome store?

Did it work before (Yes, No, I don't know): yes

#### Steps to reproduce
1. N/A

#### Expected behavior
N/A

#### Actual behavior
N/A

**Comment by AuHau** [comment]
Yeah, I think it is not actively maintained anymore. Would welcome if it would be available in Chrome store again. I wanted to do the same.

**Comment by AuHau** [comment]
Oh author even explicitly mentions it here: https://github.com/svenackermann/Prime-Player-Google-Play-Music/releases/tag/4.3

**Comment by joecross98** [comment]
Has anyone been able to install it manually (using Load Unpacked in Chrome Extensions screen)?  I gt this error: 
"Could not load javascript 'js/jquery.min.js' for content script.
Could not load manifest."

**Comment by joecross98** [comment]
Never mind, I was able to successfully install the PrimePlayer.zip file from here: https://github.com/svenackermann/Prime-Player-Google-Play-Music/releases/tag/4.3

**Comment by VeXHarbinger** [comment]
Google play is dead, so the app is neigh
